# Generated by Django 5.2.3 on 2025-07-10 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('otp_code', models.IntegerField(default=0)),
                ('otp_expire', models.DateTimeField(auto_now=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('img', models.CharField(default='', max_length=255)),
                ('banner', models.CharField(default='', max_length=255)),
                ('name', models.CharField(default='', max_length=255)),
                ('surname', models.CharField(default='', max_length=255)),
                ('description', models.CharField(default='', max_length=255)),
                ('city', models.CharField(default='', max_length=255)),
                ('school', models.CharField(default='', max_length=255)),
                ('work', models.CharField(default='', max_length=255)),
                ('website', models.CharField(default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
