# Generated by Django 5.2.3 on 2025-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='banner',
            field=models.ImageField(default='user_banner/gradient-color.jpeg', upload_to='user_banner'),
        ),
    ]
