# Generated by Django 5.2.3 on 2025-07-20 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorymodel',
            name='video_url',
            field=models.ImageField(blank=True, unique='user_story', upload_to=''),
        ),
    ]
