# Generated by Django 5.2.3 on 2025-12-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstorymodel',
            name='img_url',
            field=models.ImageField(blank=True, unique='user_story/story_img', upload_to=''),
        ),
        migrations.AlterField(
            model_name='userstorymodel',
            name='video_url',
            field=models.FileField(blank=True, unique='user_story/story_video', upload_to=''),
        ),
    ]
