# Generated by Django 5.2.3 on 2025-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstorymodel',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstorymodel',
            name='img_url',
            field=models.ImageField(blank=True, unique='user_story', upload_to=''),
        ),
    ]
