# Generated by Django 5.2.3 on 2025-07-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_story', '0002_userstorymodel_video_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstorymodel',
            old_name='story',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='userstorymodel',
            name='video_url',
            field=models.FileField(blank=True, unique='user_story', upload_to=''),
        ),
    ]
