# Generated by Django 5.2.3 on 2025-07-11 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpostmodels',
            old_name='deleted_ad',
            new_name='deleted_at',
        ),
    ]
