# Generated by Django 5.2.3 on 2025-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodels',
            name='post_video',
            field=models.ImageField(default='posts/post_vedio/post.mp4', upload_to='posts/post_vedio'),
        ),
        migrations.AlterField(
            model_name='userpostmodels',
            name='post_img',
            field=models.ImageField(default='posts/post_img/post.jpg', upload_to='posts/post_img'),
        ),
    ]
