# Generated by Django 5.2.3 on 2025-07-20 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_posts', '0002_userpostmodels_post_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpostmodels',
            name='post_img',
            field=models.ImageField(blank=True, null=True, upload_to='posts/post_img'),
        ),
        migrations.AlterField(
            model_name='userpostmodels',
            name='post_video',
            field=models.FileField(blank=True, null=True, upload_to='posts/post_vedio'),
        ),
    ]
