# Generated by Django 5.2.3 on 2025-07-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_likes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlikemodels',
            name='deleted_at',
            field=models.BooleanField(default=False),
        ),
    ]
