# Generated by Django 5.2.3 on 2025-07-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodels',
            name='post_img',
            field=models.CharField(default='', max_length=255),
        ),
    ]
